### PR TITLE
Packaging improvements

### PR DESCRIPTION
**Pull request by embray**
Updated the `setup.py` script to work a little more idiomatically, so that it can cooperate with `pip` to build pre-compiled wheel packages (the standard format for installing pre-built Python packages).

For now I also removed the pre-compiled binary builds from the git repository itself, though you could do it either way.  In this case I instead posted alpha release files as GitHub releases at:

https://github.com/embray/mic-toolbox/releases/tag/0.1.0a0

With builds for Python 3.6 and 3.7 on Windows and Linux (the two platforms I have access to).

To install the wheels you can run

    $ pip install https://github.com/embray/mic-toolbox/releases/download/0.1.0a0/mic_toolbox-0.1.0a0-cp37-cp37m-win_amd64.whl

for example.
    
Thanks to @plstrboi for testing.

### CODE REVIEW

**Comment by embray** [comment]
Also this would allow posting releases to PyPI if/when you feel it's ready.

**Comment by Sylvain-Barde** [comment]
Hi @embray 

Thanks for the improvements on the `setup.py` file and the creation of the wheels. That was something that I hadn't yet got round to looking into, and I'm sure it would have taken way more time. 

I'll look at the commits and test the `pip` installation of the wheels to make sure it all checks out, then merge everything back. Once that that is done, I'll rewrite the readme, add a few updates to the toolbox and probably generate a new release.

**Comment by embray** [comment]
Thank you, let me know if you have any questions about this.

The main idea was just to ensure that the `setup.py` works properly for use with pip, which includes only invoking Cython when running the `build_ext` command explicitly (as opposed to doing something like `setup.py --version`).

**Comment by Sylvain-Barde** [comment]
I've just tested the new setup file for compiling the extensions, as well as installing the wheel with `pip`. Everything seems to work fine, so I'm happy to merge it all back into the master.

**Pull request merged**
